apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: ms-order
  name: ms-order
  namespace: producto-digital
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: ms-order
  template: 
    metadata: 
      labels: 
        app: ms-order
    spec: 
      containers: 
        - 
          image: pdrgpd.azurecr.io/pd-sb-ms-order:0.0.2
          imagePullPolicy: Always
          volumeMounts:
          - name: secret-vol
            mountPath: "/opt/secret"
            readOnly: true
          name: ms-order
          envFrom:
          - configMapRef:
              name: ms-order-properties
          ports: 
            - 
              containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 2	
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "500m"	    			                    
      restartPolicy: Always
      volumes:
      - name: secret-vol
        configMap:
          name: ms-order-catalog
          items:
          - key: errorCatalog.json
            path: errorCatalog.json	
---
################################# Service - ClusterIp
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: ms-order
  name: ms-order
  namespace: producto-digital
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: ms-order
  type: NodePort
---